name: Postman Tests

on:
  push:
    branches:
      - main  # Run on main branch push
  pull_request:
    branches:
      - main  # Run on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Setup Containers
        run: docker-compose up -d

      - name: Wait for DynamoDB to be healthy
        run: |
          for i in {1..24}; do
            if [ "$(docker inspect -f {{.State.Health.Status}} dynamodb_local)" = "healthy" ]; then
              echo "DynamoDB is healthy"
              break
            fi
            echo "Waiting for DynamoDB to be healthy..."
            sleep 5
          done

      - name: Wait for LocalStack to be healthy
        run: |
          for i in {1..24}; do
            if [ "$(docker inspect -f {{.State.Health.Status}} laa-secure-document-storage-api_localstack_1)" = "healthy" ]; then
              echo "LocalStack is healthy"
              break
            fi
            echo "Waiting for LocalStack to be healthy..."
            sleep 5
          done

      - name: Setup S3 Bucket
        run: ./s3-bucket-create.sh

      - name: Setup AuditDB
        run: ./auditdb.sh

      - name: Upload Test File To S3
        run: aws --endpoint-url=http://localhost:4566 s3 cp README.md s3://sds-local/README

      - name: Run Postman Tests
        run: newman run ./Postman/SecureDocStoreAPI.postman_collection.json
