apiVersion: v1
kind: Service
metadata:
  name: laa-sds-service
spec:
  selector:
    app: laa-sds-api # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 8000
      targetPort: 8000