name: Linting and Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python 3.13
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv run pipenv install

    - name: Install test dependencies
      run: |
        pipenv run pipenv install --dev

    - name: Set .env file
      run: |
        cp .env.sample .env

    # Token needed to checkout client configs
    - name: Obtain Octo STS Token
      uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
      id: octo_sts
      with:
        scope: '${{ vars.CLIENT_CONFIGS_REPOSITORY }}'              # Reference to repository you want to consume
        identity: ministryofjustice-laa-secure-document-storage-api # Same as the filename in the private repo

    - name: Checkout configs repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: 'false'
        token: '${{ steps.octo_sts.outputs.token }}'
        repository: '${{ vars.CLIENT_CONFIGS_REPOSITORY }}'
        # Note path must be within the $GITHUB_WORKSPACE directory, otherwise get error
        path: './configs'
        ref: 'main'
        sparse-checkout: 'clientconfigs'

    - name: Check configs
      run: |
        ls './configs'

    - name: Lint with flake8
      run: |
        pipenv run python -m flake8 . -v

    - name: Unit test with pytest
      run: |
        pipenv run pytest --ignore tests/end_to_end -v -m "not e2e"
